backend:
  name: github
  repo: sfraney/wilderness_pathfinder_connections
  branch: main
  base_url: https://api.github.com
#  auth_scope: repo
  app_id: ${{ secrets.DECAP_CMS_CLIENT_ID }}  # Pass GitHub OAuth Client ID here
#  auth_endpoint: /login/oauth/authorize
#  cms_label_prefix: "cms"
#  open_authoring: true

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
